function state(id, key, label) {
  return { id: `drill${id}.${key}`, label, kind: "state" };
}

function action(id, key, label) {
  return { id: `drill${id}.${key}`, label, kind: "action" };
}

function drill(id, title, prompt, hint, answer, conditions, explanation) {
  return { id, title, prompt, hint, answer, explanation, conditions };
}

export const extraDrills = [
  drill(21, "衝突なしrebase", "main が進んだ状態で、feature ブランチを main の先端へ `git rebase main` で付け替えてください。", "feature に切り替えて `git rebase main` すると、feature の変更が main の最新コミットの後ろに積み直されます。", ["git switch feature", "git rebase main"], [state(21, "onFeature", "feature ブランチにいる"), state(21, "rebasedOntoMain", "feature が main の先端に付け替わっている")], "`git rebase main` は feature のコミットを一度外し、main の最新地点の後ろに順番に載せ直します。先に feature へ切り替えるのは、付け替える対象が今いるブランチだからです。共有済みブランチで使うと履歴が変わるため、個人作業の整理に向いています。"),
  drill(22, "空コミット", "`git commit --allow-empty` で空コミットを1つ作ってください。", "`--allow-empty` はファイル変更なしでもコミットを作れます。", ["git commit --allow-empty -m \"empty checkpoint\""], [state(22, "message", "最新コミットのメッセージが empty checkpoint"), action(22, "allowEmptyUsed", "git commit --allow-empty を実行した")], "`git commit --allow-empty` はファイル差分がなくても新しいコミットを作ります。通常 Git は空のコミットを拒否するため、このオプションで意図的な記録だと伝える必要があります。CI の再実行や作業開始の目印など、内容以外の区切りを残す時に使います。"),
  drill(23, "全変更をまとめる", "複数ファイルの変更を `git add -A` でまとめてステージし、コミットしてください。", "`git add -A` は追加・変更・削除をまとめてステージします。", ["printf \"alpha\\n\" > alpha.txt", "printf \"beta\\n\" > beta.txt", "git add -A", "git commit -m \"add alpha beta\""], [state(23, "filesTracked", "alpha.txt と beta.txt が HEAD にコミット済み"), action(23, "addAUsed", "git add -A を実行した")], "`git add -A` はリポジトリ全体の追加・編集・削除をまとめてステージします。複数ファイルを一つの変更単位としてコミットしたい時に、漏れを防げるのが正解です。無関係な変更も拾うため、実行前に `git status` で対象を確認すると安全です。"),
  drill(24, "追跡済みを一括コミット", "追跡済みの README.md を編集し、`git commit -am` で一括コミットしてください。", "`git commit -am` は追跡済みファイルの変更をステージしてコミットします。", ["printf \"# My Project\\nupdated\\n\" > README.md", "git commit -am \"update readme\""], [state(24, "message", "最新コミットのメッセージが update readme"), action(24, "commitAmUsed", "git commit -am を実行した")], "`git commit -am` は追跡済みファイルの変更を自動でステージし、そのままコミットします。README.md はすでに Git が知っているため、別に `git add` しなくても対象になります。新規ファイルは拾わないので、初めて作ったファイルには通常の `git add` が必要です。"),
  drill(25, "2ファイルだけコミット", "one.txt / two.txt / three.txt のうち one.txt と two.txt だけをコミットしてください。", "コミットしたいファイルだけを `git add` に指定します。", ["git add one.txt two.txt", "git commit -m \"add selected files\""], [state(25, "selectedTracked", "one.txt と two.txt が HEAD にコミット済み"), state(25, "threeUntracked", "three.txt は未追跡のまま")], "`git add one.txt two.txt` は指定した2ファイルだけをステージし、three.txt は未追跡のまま残します。コミットはステージの中身だけから作られるため、必要な変更だけを選べます。実務では別件の作業を混ぜないために、ファイル単位で選んでコミットする場面が多いです。"),
  drill(26, "amendで変更を追加", "README.md の追加変更を `git commit --amend --no-edit` で直前コミットに足してください。", "`--no-edit` はコミットメッセージを変えずに amend します。", ["printf \"# My Project\\namended\\n\" > README.md", "git add README.md", "git commit --amend --no-edit"], [state(26, "singleCommit", "コミット数が1つのまま"), action(26, "amendUsed", "git commit --amend --no-edit を実行した")], "`git commit --amend --no-edit` はステージ済みの変更を直前コミットに混ぜ込み、メッセージは変えずに作り直します。先に `git add README.md` するのは、amend に含める内容をステージで指定するためです。push 前の小さな入れ忘れ修正に向いています。"),
  drill(27, "amendで新ファイル追加", "note.txt を直前コミットに含めるよう `git commit --amend --no-edit` してください。", "新ファイルも `git add` してから amend できます。", ["printf \"note\\n\" > note.txt", "git add note.txt", "git commit --amend --no-edit"], [state(27, "noteTracked", "note.txt が HEAD にコミット済み"), state(27, "singleCommit", "コミット数が1つのまま")], "新しい note.txt も、`git add` でステージすれば直前コミットの材料にできます。`git commit --amend --no-edit` はコミット数を増やさず、既存コミットを note.txt 入りに作り直します。共有前にファイルの入れ忘れへ気づいた時の定番手順です。"),
  drill(28, "cherry-pickで取り込み", "feature にある `add report` コミットだけを main に `git cherry-pick feature` で取り込んでください。", "別ブランチの単独コミットは、main 側で `git cherry-pick <ブランチ名>` と指定して取り込めます。", ["git cherry-pick feature"], [state(28, "onMain", "main ブランチにいる"), state(28, "reportPicked", "report.txt のコミットが main に取り込まれている")], "`git cherry-pick feature` は feature が指すコミットの変更だけを、今いる main の上に新しいコミットとして再現します。ブランチ全体をマージせず必要な1件だけ選べるため、このドリルの条件に合います。取り込み元と先で同じ箇所を変えていると衝突することがあります。"),
  drill(29, "git show HEAD", "`git show HEAD` で最新コミットを確認してください。", "`git show HEAD` は最新コミットの内容を表示します。", ["git show HEAD"], [state(29, "hasCommit", "1つ以上のコミットがある"), action(29, "showHeadUsed", "git show HEAD を実行した")], "`git show HEAD` は現在の最新コミットについて、メッセージや作成者に加えて差分も表示します。`HEAD` は今いるブランチの先端を指す名前なので、直近で何が入ったかを確認するのに適しています。レビュー前の自己確認でよく使います。"),
  drill(30, "git log -1", "`git log -1` で最新コミットを1件だけ表示してください。", "`git log -1` は最新の1件だけを表示します。", ["git log -1"], [state(30, "hasCommit", "1つ以上のコミットがある"), action(30, "logOneUsed", "git log -1 を実行した")], "`git log -1` は履歴のうち最新コミット1件だけを表示します。差分までは不要で、メッセージやハッシュだけ素早く確認したい時に向いています。長い履歴のリポジトリでも出力が小さく、確認作業がしやすくなります。"),

  drill(31, "未ステージ差分", "README.md を編集し、`git diff` で未ステージ差分を確認してください。", "`git diff` はまだステージしていない変更を表示します。", ["printf \"# My Project\\ndiff\\n\" > README.md", "git diff"], [state(31, "workingDiff", "README.md に未ステージ差分がある"), action(31, "diffUsed", "git diff を実行した")], "`git diff` は作業ツリーにある未ステージ変更と、ステージまたは HEAD 側との差を表示します。今回は README.md を編集しただけなので、コミット前にどこが変わったかを確認する正しい手順です。add した後は通常の `git diff` には出にくくなる点に注意します。"),
  drill(32, "ステージ済み差分", "README.md を編集して add し、`git diff --staged` で確認してください。", "`git diff --staged` はステージ済み差分を表示します。", ["printf \"# My Project\\nstaged\\n\" > README.md", "git add README.md", "git diff --staged"], [state(32, "stagedDiff", "README.md にステージ済み差分がある"), action(32, "diffStagedUsed", "git diff --staged を実行した")], "`git add README.md` で変更をステージに載せると、通常の `git diff` ではなく `git diff --staged` で確認します。これは次のコミットに入る内容を表示するため、コミット直前の確認に向いています。間違いを見つけたらステージを外して直せます。"),
  drill(33, "HEADとの差分", "README.md を編集し、`git diff HEAD` で全差分を確認してください。", "`git diff HEAD` は作業ツリーと最新コミットの差分を表示します。", ["printf \"# My Project\\nhead diff\\n\" > README.md", "git diff HEAD"], [state(33, "headDiff", "README.md が HEAD から変更されている"), action(33, "diffHeadUsed", "git diff HEAD を実行した")], "`git diff HEAD` は最新コミットと現在の作業全体との差分を表示します。未ステージとステージ済みの両方をまとめて見られるため、HEAD から何が変わったかを確認する条件に合います。コミット前の最終確認に便利です。"),
  drill(34, "直近コミット差分", "`git diff HEAD~1 HEAD` で直近コミットの差分を確認してください。", "`HEAD~1 HEAD` を指定すると直近1コミット分の差分を見られます。", ["git diff HEAD~1 HEAD"], [state(34, "twoCommits", "2つ以上のコミットがある"), action(34, "diffRangeUsed", "git diff HEAD~1 HEAD を実行した")], "`git diff HEAD~1 HEAD` は1つ前のコミットと現在の最新コミットを比べます。範囲を明示することで、直近コミットで入った変更だけを切り出して確認できます。レビュー前に最後の1コミットの内容を見直す時に役立ちます。"),
  drill(35, "onelineログ", "`git log --oneline` で履歴を短く表示してください。", "`--oneline` はコミットを1行ずつ表示します。", ["git log --oneline"], [state(35, "hasCommit", "1つ以上のコミットがある"), action(35, "logOnelineUsed", "git log --oneline を実行した")], "`git log --oneline` は各コミットを短いハッシュとメッセージの1行で表示します。履歴全体の流れを素早く見る目的では、詳細なログより読みやすいのが正解です。コミットを指定して戻す時の目印探しにもよく使います。"),
  drill(36, "stat付きログ", "`git log --stat` で変更ファイル数つきの履歴を確認してください。", "`--stat` はコミットごとの変更量を表示します。", ["git log --stat"], [state(36, "hasCommit", "1つ以上のコミットがある"), action(36, "logStatUsed", "git log --stat を実行した")], "`git log --stat` は各コミットの情報に加えて、どのファイルがどれくらい変わったかを集計表示します。差分本文までは見ずに変更規模を把握したい時に適しています。大きすぎるコミットや意図しないファイル混入の発見に役立ちます。"),
  drill(37, "2件ログ", "`git log -n 2` で最新2件の履歴を確認してください。", "`-n 2` は表示するコミット数を2件に絞ります。", ["git log -n 2"], [state(37, "twoCommits", "2つ以上のコミットがある"), action(37, "logN2Used", "git log -n 2 を実行した")], "`git log -n 2` は最新から2件だけコミット履歴を表示します。必要な範囲だけに絞ることで、長い履歴の中でも直近の流れを確認しやすくなります。直前の作業や amend 前後の確認に使いやすい指定です。"),
  drill(38, "特定コミットをshow", "最新コミットのOIDを使って `git show <oid>` を実行してください。", "`git rev-parse HEAD` でOIDを取り、`git show` に渡せます。", ["git show $(git rev-parse HEAD)"], [state(38, "hasCommit", "1つ以上のコミットがある"), action(38, "showUsed", "git show <oid> を実行した")], "`git rev-parse HEAD` は最新コミットの正式な OID を出力し、それを `git show` に渡すと対象コミットの詳細を表示できます。名前ではなくIDで指定する練習なので、どのコミットを見るかが曖昧になりません。実務ではログで見つけたハッシュの中身確認に使います。"),
  drill(39, "graphログ", "`git log --oneline --graph` でグラフ表示してください。", "`--graph` はブランチやマージの形をASCIIグラフで表示します。", ["git log --oneline --graph"], [state(39, "hasCommit", "1つ以上のコミットがある"), action(39, "logGraphUsed", "git log --oneline --graph を実行した")], "`git log --oneline --graph` は短いログに枝分かれやマージの形を線で添えて表示します。ブランチがどう合流したかを見るには、単なる時系列より構造が分かりやすくなります。マージや rebase の結果確認でよく使います。"),
  drill(40, "ファイル別履歴", "`git log -- README.md` で README.md の履歴だけを表示してください。", "`git log -- ファイル名` は対象ファイルに関係する履歴だけを表示します。", ["git log -- README.md"], [state(40, "readmeTracked", "README.md が HEAD にコミット済み"), action(40, "logFileUsed", "git log -- README.md を実行した")], "`git log -- README.md` は README.md に関係するコミットだけを表示します。`--` 以降をパスとして扱うため、ブランチ名などとの混同を避けられます。特定ファイルの変更理由や時期を調べる時に便利です。"),

  drill(41, "ブランチ作成だけ", "`git branch experiment` で切り替えずにブランチを作ってください。", "`git branch 名前` は現在位置にブランチを作るだけで切り替えません。", ["git branch experiment"], [state(41, "branchExists", "experiment ブランチがある"), state(41, "onMain", "main ブランチにいる")], "`git branch experiment` は現在のコミットに experiment というブランチ名を追加します。作成だけで移動はしないため、main にいる条件を保ったまま準備できます。後で作業を始めたい分岐点だけ先に作る時に使います。"),
  drill(42, "switch -c", "`git switch -c feature/a` でブランチを作って切り替えてください。", "`git switch -c` は作成と切り替えを同時に行います。", ["git switch -c feature/a"], [state(42, "branchExists", "feature/a ブランチがある"), state(42, "onBranch", "feature/a ブランチにいる")], "`git switch -c feature/a` は新しい feature/a ブランチを作り、そのまま作業先を切り替えます。作成後すぐにそのブランチでコミットしたい場合、別々に `branch` と `switch` を打つより手順が明確です。新しい Git ではブランチ移動に `switch` を使うと意図が読みやすくなります。"),
  drill(43, "checkout -b", "`git checkout -b feature/b` でブランチを作って切り替えてください。", "`git checkout -b` は古くから使われる作成・切り替えコマンドです。", ["git checkout -b feature/b"], [state(43, "branchExists", "feature/b ブランチがある"), state(43, "onBranch", "feature/b ブランチにいる")], "`git checkout -b feature/b` は feature/b を作成し、同時にそのブランチへ移動します。`switch -c` と同じ目的ですが、古い資料や現場では checkout 形式もよく見かけます。checkout は他の用途も多いので、ブランチ操作だと分かるように `-b` の意味を押さえると安全です。"),
  drill(44, "リモート確認", "`git remote -v` で origin の接続先を確認してください。", "`git remote -v` は fetch/push に使うリモートURLを表示します。", ["git remote -v"], [state(44, "originConfigured", "origin リモートが設定されている"), action(44, "remoteVUsed", "git remote -v を実行した")], "`git remote -v` は origin などのリモート名と、取得や送信に使う URL を表示します。push 先を間違えないため、送信前に接続先を確認するのは実務で重要です。fetch と push で別URLが設定されている場合もあるため、`-v` で両方を見るのが適切です。"),
  drill(45, "mainに戻る", "作業ブランチから main に戻ってください。", "`git switch main` で main ブランチへ戻れます。", ["git switch main"], [state(45, "onMain", "main ブランチにいる"), state(45, "featureExists", "feature ブランチが残っている")], "`git switch main` は現在の作業先を main ブランチへ切り替えます。ブランチを移動しても feature ブランチ自体は削除されないため、作業履歴は残ります。マージやリリース作業の前には、今どのブランチにいるかを確認してから切り替えるのが安全です。"),
  drill(46, "マージ済み削除", "マージ済みの feature ブランチを `git branch -d` で削除してください。", "`-d` はマージ済みブランチを安全に削除します。", ["git branch -d feature"], [state(46, "featureGone", "feature ブランチが残っていない"), action(46, "branchDeleteUsed", "git branch -d を実行した")], "`git branch -d feature` はローカルの feature ブランチを削除します。`-d` は未マージの変更があると止めるため、マージ済みブランチの片付けに向いた安全な指定です。削除しても取り込まれたコミットは main 側に残ります。"),
  drill(47, "未マージ強制削除", "未マージの wip ブランチを `git branch -D` で強制削除してください。", "`-D` は未マージでも削除する強い操作です。", ["git branch -D wip"], [state(47, "wipGone", "wip ブランチが残っていない"), action(47, "branchForceDeleteUsed", "git branch -D を実行した")], "`git branch -D wip` は未マージの変更があってもブランチ名を強制削除します。通常の `-d` では守られる作業も消せてしまうため、不要だと判断できる時だけ使うのが正解です。実務では削除前に `git log wip` などで中身を確認します。"),
  drill(48, "ブランチ改名", "`git branch -m feature/old feature/new` でブランチ名を変えてください。", "`git branch -m 旧名 新名` でブランチを改名できます。", ["git branch -m feature/old feature/new"], [state(48, "newExists", "feature/new ブランチがある"), state(48, "oldGone", "feature/old ブランチが残っていない")], "`git branch -m feature/old feature/new` はブランチが指すコミットはそのままに、名前だけを変更します。古い名前を新しい名前に置き換える操作なので、old が消えて new が残る状態になります。リモートに公開済みの場合は、リモート側の削除や上流設定の見直しも必要です。"),
  drill(49, "初回push", "`git push -u origin main` で main を origin に送信し、上流ブランチを設定してください。", "`-u` を付けると次回以降 `git push` / `git pull` だけで origin/main と同期しやすくなります。", ["git push -u origin main"], [state(49, "originMainHasHead", "origin/main が現在の main を指している"), state(49, "mainUpstream", "main の上流が origin/main に設定されている")], "`git push -u origin main` はローカル main を origin に送り、main の上流を origin/main に設定します。初回に `-u` を付けると、次から `git push` や `git pull` だけで相手先を推測できます。リモート共有を始める最初の push でよく使います。"),
  drill(50, "featureを2コミット進める", "feature ブランチで2つコミットを作ってください。", "ブランチへ切り替えてから通常通り2回コミットします。", ["git switch feature", "printf \"one\\n\" > f1.txt", "git add f1.txt", "git commit -m \"feature one\"", "printf \"two\\n\" > f2.txt", "git add f2.txt", "git commit -m \"feature two\""], [state(50, "onFeature", "feature ブランチにいる"), state(50, "aheadTwo", "feature が main より2つ以上進んでいる")], "先に `git switch feature` することで、以後のコミットは feature ブランチの先端に積まれます。2回 add/commit するため、main より2コミット進んだ状態になります。変更を小さく分けると、後から内容を確認したり取り消したりしやすくなります。"),
  drill(51, "特定コミットから分岐", "1つ前のコミットから `git switch -c rescue HEAD~1` でブランチを切ってください。", "`git switch -c 名前 <開始点>` で任意のコミットから分岐できます。", ["git switch -c rescue HEAD~1"], [state(51, "branchExists", "rescue ブランチがある"), state(51, "onBranch", "rescue ブランチにいる")], "`git switch -c rescue HEAD~1` は最新の1つ前のコミットを開始点にして rescue ブランチを作り、そこへ移動します。HEAD の位置ではなく明示した地点から分岐するため、過去の状態を起点に作業できます。直近変更を避けて修正や調査を始めたい時に便利です。"),
  drill(52, "現在ブランチ名", "`git branch --show-current` で現在のブランチ名を確認してください。", "`--show-current` は今いるブランチ名だけを表示します。", ["git branch --show-current"], [state(52, "onMain", "main ブランチにいる"), action(52, "showCurrentUsed", "git branch --show-current を実行した")], "`git branch --show-current` は現在いるブランチ名だけを出力します。一覧表示より結果が短いため、スクリプトや確認作業で扱いやすいのが正解です。コミットやマージの前に作業先を取り違えていないか確認する習慣が大切です。"),
  drill(53, "hotfixブランチ", "main から hotfix ブランチを作って切り替えてください。", "`git switch -c hotfix` で main から修正用ブランチを作れます。", ["git switch -c hotfix"], [state(53, "hotfixExists", "hotfix ブランチがある"), state(53, "onHotfix", "hotfix ブランチにいる")], "`git switch -c hotfix` は現在の main から hotfix ブランチを作り、そのまま移動します。緊急修正を main から分けることで、通常開発とは独立して小さく直せます。作成前に main が最新か確認しておくと、古い状態から修正を始める事故を避けられます。"),
  drill(54, "別ファイルをコミット", "feature ブランチに切り替え、feature.txt をコミットしてください。", "ブランチを切り替えると、そのブランチ専用の変更を作れます。", ["git switch feature", "printf \"feature\\n\" > feature.txt", "git add feature.txt", "git commit -m \"add feature file\""], [state(54, "onFeature", "feature ブランチにいる"), state(54, "featureFileTracked", "feature.txt が HEAD にコミット済み")], "`git switch feature` で作業先を feature にしてからファイルを追加するため、コミットは feature 側に記録されます。`git add` と `git commit` の順で、作った feature.txt を履歴に確定します。ブランチを分けると、main を汚さず機能作業を進められます。"),
  drill(55, "直前ブランチへ戻る", "`git switch -` で直前にいたブランチへ戻ってください。", "`git switch -` は直前のブランチへ戻るショートカットです。", ["git switch -"], [state(55, "onMain", "main ブランチに戻っている"), action(55, "switchDashUsed", "git switch - を実行した")], "`git switch -` は直前にいたブランチへ戻るショートカットです。ブランチ名を打たずに戻れるため、feature と main を行き来する確認作業で便利です。ただし直前の移動先に依存するので、実行後に現在ブランチを確認すると安全です。"),

  drill(56, "FFマージ", "main に feature を fast-forward マージしてください。", "`git merge --ff-only feature` はFFできる時だけ履歴を進めます。", ["git merge --ff-only feature"], [state(56, "onMain", "main ブランチにいる"), state(56, "featureMerged", "feature の変更が main に入っている")], "`git merge --ff-only feature` は main を feature の先端へ動かせる場合だけ取り込みます。余分なマージコミットを作らないので、履歴を直線に保ちたい条件に合います。FFできない時は失敗するため、意図しない複雑なマージを避ける確認にもなります。"),
  drill(57, "no-ffマージ", "`git merge --no-ff feature` でマージコミットを作ってください。", "`--no-ff` はFF可能でもマージコミットを残します。", ["git merge --no-ff feature -m \"merge feature\""], [state(57, "onMain", "main ブランチにいる"), state(57, "mergeCommit", "マージコミットが作られている")], "`git merge --no-ff feature` は fast-forward 可能でも必ずマージコミットを作ります。`-m` でメッセージを指定しているため、マージの意味を履歴に残せます。機能ブランチ単位の作業を後から見つけやすくしたい時に使います。"),
  drill(58, "README衝突解決", "README.md の衝突を解決して feature をマージしてください。", "衝突マーカーを消して `git add`、最後に `git commit` します。", ["git merge feature", "printf \"# My Project\\nmain line\\nfeature line\\n\" > README.md", "git add README.md", "git commit -m \"merge feature\""], [state(58, "noMarkers", "README.md に衝突マーカーがない"), state(58, "mergeCommit", "マージコミットが作られている")], "`git merge feature` で README.md の同じ場所が競合すると、Git は判断を止めて解決待ちにします。完成形の内容を書き直し、`git add README.md` で解決済みとして登録してからコミットします。衝突マーカーが残るとファイル内容として混入するため、必ず消します。"),
  drill(59, "別ファイル衝突解決", "config.txt の衝突を解決して feature をマージしてください。", "README以外でも解決手順は同じです。", ["git merge feature", "printf \"mode=main\\nmode=feature\\n\" > config.txt", "git add config.txt", "git commit -m \"merge config\""], [state(59, "noMarkers", "config.txt に衝突マーカーがない"), state(59, "mergeCommit", "マージコミットが作られている")], "config.txt の衝突も、README.md と同じく人が最終内容を決める必要があります。ファイルを整えて `git add config.txt` すると、Git に解決済みだと伝えられます。設定ファイルの衝突は動作に直結しやすいので、両方の値を残すべきか特に確認します。"),
  drill(60, "マージ中止", "衝突したマージを `git merge --abort` で中止してください。", "`git merge --abort` はマージ開始前の状態へ戻します。", ["git merge feature", "git merge --abort"], [state(60, "clean", "作業ツリーが clean"), action(60, "mergeAbortUsed", "git merge --abort を実行した")], "`git merge --abort` は進行中のマージを取り消し、可能な限りマージ開始前の状態へ戻します。衝突解決を続けず最初からやり直したい条件なので、この操作が適切です。マージ前に未コミット変更があると戻しにくい場合があるため、事前に clean にしておくのが安全です。"),
  drill(61, "3つ目のブランチをマージ", "feature/c を main にマージしてください。", "対象ブランチ名を指定して `git merge feature/c` します。", ["git merge feature/c"], [state(61, "onMain", "main ブランチにいる"), state(61, "cMerged", "feature/c の変更が main に入っている")], "`git merge feature/c` は今いる main に feature/c の変更を取り込みます。マージは現在ブランチへ相手ブランチを統合する操作なので、main にいることが前提になります。複数ブランチがある時は、取り込みたい名前を正確に指定することが大切です。"),
  drill(62, "マージ後ログ確認", "feature をマージし、`git log --oneline` で確認してください。", "マージ後の履歴確認には `git log --oneline` が便利です。", ["git merge --ff-only feature", "git log --oneline"], [state(62, "featureMerged", "feature の変更が main に入っている"), action(62, "logOnelineUsed", "git log --oneline を実行した")], "まず `git merge --ff-only feature` で feature の変更を main に取り込みます。その後 `git log --oneline` を見ると、取り込まれたコミットが履歴に現れたか短く確認できます。マージ直後にログを見る習慣は、取り込み先や内容の勘違いを防ぎます。"),
  drill(63, "pullで取り込む", "origin/main にある teammate.txt の更新を `git pull` で取り込んでください。", "ローカル main が origin/main より遅れている時は `git pull` で fetch と統合をまとめて実行できます。", ["git pull"], [state(63, "pulledTeammate", "teammate.txt が main に取り込まれている"), state(63, "mainMatchesOrigin", "main と origin/main が同じコミットを指している")], "`git pull` はリモートの新着を取得する `fetch` と、現在ブランチへの統合をまとめて行います。origin/main の teammate.txt をローカル main に反映したいので、この一手で条件を満たせます。作業中の変更があると衝突しやすいため、pull 前は状態確認が重要です。"),
  drill(64, "2機能を順にマージ", "feature/a と feature/b を順番に main へマージしてください。", "複数ブランチは1本ずつ `git merge` します。", ["git merge feature/a", "git merge feature/b"], [state(64, "aMerged", "feature/a の変更が main に入っている"), state(64, "bMerged", "feature/b の変更が main に入っている")], "`git merge feature/a` の後に `git merge feature/b` を実行すると、main に2本の機能ブランチを順番に取り込めます。一度に混ぜず1本ずつ進めることで、どちらの取り込みで問題が起きたか分かりやすくなります。実務でも複数機能は順に統合して確認します。"),
  drill(65, "通常マージコミット", "main 側も進んだ状態で feature を通常マージし、マージコミットを作ってください。", "双方が進んでいる場合、通常の `git merge` はマージコミットを作ります。", ["git merge feature -m \"merge feature\""], [state(65, "onMain", "main ブランチにいる"), state(65, "mergeCommit", "マージコミットが作られている")], "main と feature の両方に別々のコミットがある時、`git merge feature` は2つの流れを結ぶマージコミットを作ります。`-m` でメッセージを指定することで、統合の意味をその場で記録できます。枝分かれした履歴を残したまま安全に合わせる標準的な方法です。"),

  drill(66, "編集破棄", "README.md の編集を `git restore README.md` で破棄してください。", "`git restore <file>` は未ステージ編集を破棄します。", ["git restore README.md"], [state(66, "clean", "作業ツリーが clean"), action(66, "restoreUsed", "git restore を実行した")], "`git restore README.md` は README.md を最新コミットの内容に戻し、未ステージの編集を捨てます。コミットやステージには触れず作業ツリーだけを戻すため、試した変更をなかったことにする条件に合います。破棄した内容は戻しにくいので、必要な変更がないか確認します。"),
  drill(67, "ステージ解除", "README.md のステージだけを `git restore --staged README.md` で解除してください。", "`--staged` は内容を残してステージだけ外します。", ["git restore --staged README.md"], [state(67, "noStaged", "ステージ済み差分がない"), state(67, "workingDiff", "作業ツリーに変更が残っている")], "`git restore --staged README.md` はステージに載せた README.md を次のコミット候補から外します。作業ツリーの編集は残るため、内容を失わずコミット対象だけ調整できます。間違って add した時に安全に戻すための操作です。"),
  drill(68, "soft reset", "`git reset --soft HEAD~1` で直前コミットを戻し、変更をステージに残してください。", "`--soft` はHEADだけを戻すので変更はステージに残ります。", ["git reset --soft HEAD~1"], [state(68, "oneCommit", "コミット数が1つ戻っている"), state(68, "staged", "変更がステージに残っている")], "`git reset --soft HEAD~1` はブランチの先端だけを1つ前へ戻し、直前コミットの内容はステージに残します。すぐ再コミットできる状態を保つため、コミットメッセージやまとめ方を直したい時に合います。共有済み履歴では使いどころに注意します。"),
  drill(69, "mixed reset", "`git reset --mixed HEAD~1` で直前コミットを戻し、変更を未ステージにしてください。", "`--mixed` はHEADとインデックスを戻し、作業ツリーに変更を残します。", ["git reset --mixed HEAD~1"], [state(69, "oneCommit", "コミット数が1つ戻っている"), state(69, "workingDiff", "変更が未ステージに残っている")], "`git reset --mixed HEAD~1` は直前コミットを取り消し、ステージも1つ前の状態へ戻します。変更内容は作業ツリーに残るため、どのファイルを add し直すか選び直せます。`git reset` の標準に近い挙動で、コミットを分け直す時に便利です。"),
  drill(70, "hard reset", "`git reset --hard HEAD~1` で直前コミットと変更を完全に戻してください。", "`--hard` は作業ツリーも消す強い操作です。必要な変更がない時だけ使います。", ["git reset --hard HEAD~1"], [state(70, "oneCommit", "コミット数が1つ戻っている"), state(70, "clean", "作業ツリーが clean")], "`git reset --hard HEAD~1` は HEAD、ステージ、作業ツリーをまとめて1つ前の状態に戻します。直前コミットの変更も手元の編集も残さないため、clean に戻したい条件に合います。未保存の作業を失う強い操作なので、本当に不要な時だけ使います。"),
  drill(71, "revertで打ち消し", "`git revert HEAD --no-edit` で直前コミットを打ち消してください。", "`git revert` は履歴を消さずに逆変更のコミットを追加します。", ["git revert HEAD --no-edit"], [state(71, "badGone", "bad.txt が消えている"), state(71, "revertCommit", "revertコミットが追加されている")], "`git revert HEAD --no-edit` は直前コミットと逆の変更を作り、新しいコミットとして追加します。履歴は残したまま bad.txt を消した状態にできるので、共有済みの変更を取り消す時に安全です。`--no-edit` は自動メッセージのまま確定する指定です。"),
  drill(72, "別コミットをrevert", "`git revert HEAD~1 --no-edit` で1つ前のコミットを打ち消してください。", "HEAD以外のコミットも指定して revert できます。", ["git revert HEAD~1 --no-edit"], [state(72, "oldGone", "old-bug.txt が消えている"), state(72, "revertCommit", "revertコミットが追加されている")], "`git revert HEAD~1 --no-edit` は最新ではなく1つ前のコミットを指定して打ち消します。対象コミットだけの逆変更を新しいコミットにするため、履歴を消さず old-bug.txt の追加を取り消せます。間に別変更がある場合は衝突することがあるため、内容確認が必要です。"),
  drill(73, "reflog確認", "`git reflog` でHEAD移動履歴を確認してください。", "`git reflog` はreset前後のHEAD位置を探す時に便利です。", ["git reflog"], [state(73, "hasCommit", "1つ以上のコミットがある"), action(73, "reflogUsed", "git reflog を実行した")], "`git reflog` はブランチや HEAD が過去にどのコミットを指していたかをローカルに記録した一覧を表示します。reset や amend で通常のログから見えにくくなった地点も探せるため、復旧の手がかりになります。ローカル記録なので、永久に残るバックアップではありません。"),
  drill(74, "reflogから復活", "失われた recover.txt のコミットを reflog から見つけ、`git reset --hard <oid>` か `git reset --hard ORIG_HEAD` で復活させてください。", "`git reflog` で reset 前の位置を探し、そのOIDへ `git reset --hard` します。", ["git reflog", "git reset --hard ORIG_HEAD"], [state(74, "recoverTracked", "recover.txt が HEAD にコミット済み"), state(74, "recoverHead", "HEAD が recover.txt の復旧コミットに戻っている")], "`git reflog` で reset 前に HEAD が指していたコミットを探し、`git reset --hard ORIG_HEAD` などでそこへ戻します。recover.txt を含むコミットそのものへ HEAD を戻すため、失われたように見えた内容を復活できます。`--hard` は現在の作業を消すので、退避してから使うのが安全です。"),
  drill(75, "削除ファイル復元", "削除した README.md を `git restore README.md` で復元してください。", "追跡済みファイルの削除も `git restore` でHEADから戻せます。", ["git restore README.md"], [state(75, "readmeExists", "README.md が存在する"), state(75, "clean", "作業ツリーが clean")], "`git restore README.md` は HEAD に記録されている README.md を作業ツリーへ戻します。追跡済みファイルを誤って削除した場合も、最新コミットにある内容から復元できるため条件に合います。未追跡ファイルは Git に記録がないため、この方法では戻せません。"),
  drill(76, "fetchして確認", "origin/main の新着コミットを `git fetch` で取得し、`git log --oneline origin/main` で確認してください。", "`git fetch` は作業ブランチを動かさずにリモート追跡ブランチだけ更新します。", ["git fetch origin", "git log --oneline origin/main"], [state(76, "originFetched", "origin/main に remote-only.txt のコミットが見えている"), action(76, "logOriginUsed", "git log origin/main を実行した")], "`git fetch origin` はリモートの情報を取得し、origin/main などのリモート追跡ブランチを更新します。ローカル main は動かさないため、取り込む前に `git log --oneline origin/main` で新着を確認できます。pull より慎重に状況を見たい時に使います。"),
  drill(77, "reset HEADでアンステージ", "README.md を `git reset HEAD README.md` でアンステージしてください。", "`git reset HEAD <file>` は古くから使われるステージ解除です。", ["git reset HEAD README.md"], [state(77, "noStaged", "ステージ済み差分がない"), state(77, "workingDiff", "作業ツリーに変更が残っている")], "`git reset HEAD README.md` は README.md のステージ状態を HEAD に戻し、コミット候補から外します。ファイル内容は作業ツリーに残るため、編集を失わず add だけ取り消せます。現在は `git restore --staged` も使えますが、古い手順として現場でよく見かけます。"),
  drill(78, "未追跡をclean", "未追跡の scratch.txt を `git clean -f` で削除してください。", "`git clean -f` は未追跡ファイルを削除する強い操作です。", ["git clean -f"], [state(78, "scratchGone", "scratch.txt が存在しない"), action(78, "cleanUsed", "git clean -f を実行した")], "`git clean -f` は Git が追跡していないファイルを作業ツリーから削除します。scratch.txt は未追跡なので、reset や restore ではなく clean の対象になります。削除後は戻せないことが多いため、実務では先に `git clean -n` で確認すると安全です。"),

  drill(79, "stashで退避", "README.md の編集を `git stash` で退避してください。", "`git stash` は作業中の変更を一時保存して作業ツリーをcleanにします。", ["git stash"], [state(79, "clean", "作業ツリーが clean"), action(79, "stashUsed", "git stash を実行した")], "`git stash` は未コミットの変更を一時的な保管場所へ移し、作業ツリーを clean に戻します。README.md の編集をまだコミットしたくないが、別作業に移りたい条件に合います。標準では未追跡ファイルは含まれない点に注意します。"),
  drill(80, "stash pop", "退避済みの作業を `git stash pop` で戻してください。", "`git stash pop` はstashを適用して一覧から取り除きます。", ["git stash pop"], [state(80, "workingDiff", "作業ツリーに変更が戻っている"), action(80, "stashPopUsed", "git stash pop を実行した")], "`git stash pop` は最新の stash を作業ツリーに適用し、成功すると stash 一覧から削除します。退避していた変更を作業に戻したい条件なので、apply ではなく pop が合っています。戻す先のファイルが変わっていると衝突することがあります。"),
  drill(81, "stash list", "`git stash list` で退避一覧を確認してください。", "`git stash list` は保存済みstashを一覧表示します。", ["git stash list"], [state(81, "stashExists", "stash が1件以上ある"), action(81, "stashListUsed", "git stash list を実行した")], "`git stash list` は保存されている stash を新しい順に一覧表示します。複数回退避している時、どの作業を戻すか確認するために先に見るのが適切です。stash 名は `stash@{0}` のように変わるので、操作前に一覧で確認します。"),
  drill(82, "stash apply", "`git stash apply` で退避を作業ツリーに適用してください。", "`git stash apply` はstashを残したまま変更を戻します。", ["git stash apply"], [state(82, "workingDiff", "作業ツリーに変更が戻っている"), state(82, "stashExists", "stash が残っている")], "`git stash apply` は stash の内容を作業ツリーへ戻しますが、stash 自体は削除しません。同じ退避内容を別ブランチでも試したい場合など、保険を残したい条件に合います。不要になったら後で `git stash drop` して整理します。"),
  drill(83, "stash drop", "`git stash drop` で退避を1件削除してください。", "`git stash drop` は指定したstashを一覧から削除します。", ["git stash drop"], [state(83, "stashEmpty", "stash が空になっている"), action(83, "stashDropUsed", "git stash drop を実行した")], "`git stash drop` は最新または指定した stash を一覧から削除します。退避内容をもう使わない場合に片付ける操作なので、stash が空になる条件に合います。削除すると戻せないことが多いため、必要な変更を適用済みか確認します。"),
  drill(84, "未追跡もstash", "未追跡の draft.txt も含めて `git stash -u` で退避してください。", "`git stash -u` は未追跡ファイルも退避対象にします。", ["git stash -u"], [state(84, "draftGone", "draft.txt が作業ツリーから消えている"), action(84, "stashUUsed", "git stash -u を実行した")], "`git stash -u` は通常の変更に加えて、まだ Git が追跡していない draft.txt も退避します。標準の `git stash` では未追跡ファイルが残るため、この条件では `-u` が必要です。生成物まで含めたい場合はさらに別指定がありますが、必要以上に退避しないことが大切です。"),
  drill(85, "stashして切替え", "変更をstashし、featureへ切り替えてから main に戻ってください。", "変更が邪魔な時はstashしてからブランチを切り替えます。", ["git stash", "git switch feature", "git switch main"], [state(85, "onMain", "main ブランチに戻っている"), action(85, "stashUsed", "git stash を実行した")], "先に `git stash` すると未コミット変更を一時保存でき、ブランチ切り替え時の衝突や拒否を避けやすくなります。その後 feature に移動し、最後に main へ戻ることで、作業先は main に戻ります。切り替え前の変更を後で使うなら stash の存在を忘れないようにします。"),
  drill(86, "cherry-pickで修正移植", "hotfix ブランチの `fix config` コミットを main に cherry-pick してください。", "緊急修正など、必要な1コミットだけを別ブランチへ移す時に `git cherry-pick` を使います。", ["git cherry-pick hotfix"], [state(86, "onMain", "main ブランチにいる"), state(86, "configPicked", "config.txt の修正コミットが main に取り込まれている")], "`git cherry-pick hotfix` は hotfix が指す修正コミットの変更を、今いる main に新しいコミットとして適用します。ブランチ全体をマージせず config.txt の修正だけを移せるため、緊急修正の取り込みに向いています。適用先で同じ箇所が変わっていると衝突します。"),
  drill(87, "stash show", "`git stash show` で退避内容の概要を確認してください。", "`git stash show` はstashの変更概要を表示します。", ["git stash show"], [state(87, "stashExists", "stash が1件以上ある"), action(87, "stashShowUsed", "git stash show を実行した")], "`git stash show` は最新 stash に含まれる変更ファイルや変更量の概要を表示します。戻す前に何を退避したか確認できるため、間違った stash を適用するリスクを減らせます。詳細な差分が必要な時は `-p` を付けて確認します。"),
  drill(88, "stash clear", "`git stash clear` でstashをすべて削除してください。", "`git stash clear` はstash一覧を全削除します。", ["git stash clear"], [state(88, "stashEmpty", "stash が空になっている"), action(88, "stashClearUsed", "git stash clear を実行した")], "`git stash clear` は保存されている stash をすべて削除します。1件ずつではなく一覧全体を空にする操作なので、不要な退避をまとめて片付ける条件に合います。復元が難しい強い操作のため、必要な stash がないと確認してから使います。"),

  drill(89, "軽量タグ", "`git tag v1.0.0` で軽量タグを作ってください。", "`git tag タグ名` は現在のコミットへ軽量タグを付けます。", ["git tag v1.0.0"], [state(89, "tagExists", "v1.0.0 タグがある"), action(89, "tagUsed", "git tag v1.0.0 を実行した")], "`git tag v1.0.0` は現在のコミットに v1.0.0 という固定の名前を付けます。軽量タグはブランチのように動かさず、特定時点を指す目印として使います。リリース地点を素早く示したい時に便利ですが、説明を残したい時は注釈タグを使います。"),
  drill(90, "注釈タグ", "`git tag -a v1.1.0 -m \"release v1.1.0\"` で注釈タグを作ってください。", "`-a -m` を使うとメッセージ付きの注釈タグを作れます。", ["git tag -a v1.1.0 -m \"release v1.1.0\""], [state(90, "tagExists", "v1.1.0 タグがある"), action(90, "annotatedTagUsed", "git tag -a を実行した")], "`git tag -a v1.1.0 -m ...` はタグ専用のメタ情報とメッセージを持つ注釈タグを作ります。リリース名だけでなく説明も残せるため、正式なリリース地点を示すのに適しています。共有するには別途タグを push する必要があります。"),
  drill(91, "タグ一覧", "`git tag` でタグ一覧を確認してください。", "`git tag` はタグ名の一覧を表示します。", ["git tag"], [state(91, "tagExists", "v1.0.0 タグがある"), action(91, "tagListUsed", "git tag を実行した")], "`git tag` はリポジトリにあるタグ名を一覧表示します。どのリリース地点が存在するかを確認するだけなら、詳細ログより簡潔です。タグが多い場合はパターン指定や並び替えを使うと探しやすくなります。"),
  drill(92, "タグ削除", "`git tag -d v1.0.0` でタグを削除してください。", "`git tag -d タグ名` はローカルタグを削除します。", ["git tag -d v1.0.0"], [state(92, "tagGone", "v1.0.0 タグが残っていない"), action(92, "tagDeleteUsed", "git tag -d を実行した")], "`git tag -d v1.0.0` はローカルにある v1.0.0 タグを削除します。コミット本体は消えず、名前の目印だけが外れるため、この条件ではタグが残らない状態になります。リモートへ送ったタグは別途リモート削除が必要です。"),
  drill(93, "logをignore", ".gitignore で `*.log` を除外してコミットしてください。", "無視パターンは `.gitignore` に書き、.gitignore自体はコミットします。", ["printf \"*.log\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore logs\""], [state(93, "gitignore", ".gitignore に *.log がある"), state(93, "debugIgnored", "debug.log がstatusに出ない")], "`.gitignore` に `*.log` を書くと、debug.log のようなログファイルが未追跡の雑音として出にくくなります。ignore ルールを `git add` してコミットすることで、チーム全員が同じ除外設定を使えます。すでに追跡済みのログは別途追跡解除が必要です。"),
  drill(94, "distをignore", ".gitignore で `dist/` ディレクトリを除外してコミットしてください。", "ディレクトリ除外は `dist/` のように末尾スラッシュを使います。", ["printf \"dist/\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore dist\""], [state(94, "gitignore", ".gitignore に dist/ がある"), state(94, "distIgnored", "dist/app.js がstatusに出ない")], "`.gitignore` に `dist/` と書くと、dist ディレクトリ配下の生成物をまとめて無視できます。末尾のスラッシュでディレクトリを意図していることが分かり、ビルド成果物を履歴に混ぜにくくなります。ソースではなく再生成できるものを除外する時に使います。"),
  drill(95, "追跡解除", "`git rm --cached secret.txt` でファイルを残したまま追跡解除してください。", "`--cached` は作業ツリーのファイルを残してGitの追跡だけ外します。", ["git rm --cached secret.txt"], [state(95, "secretUntracked", "secret.txt が追跡対象から外れている"), state(95, "secretExists", "secret.txt は作業ツリーに残っている")], "`git rm --cached secret.txt` は Git の管理対象から secret.txt を外しますが、手元のファイルは削除しません。消したいのは履歴への追跡であって作業ツリーの実体ではないため、`--cached` が必要です。秘密情報を扱う場合は、過去履歴に残った内容の対処も別途考えます。"),

  drill(96, "hotfix実務フロー", "main で bugfix.txt を修正して1コミットしてください。", "hotfixは小さく修正し、すぐコミットするのが基本です。", ["printf \"fixed\\n\" > bugfix.txt", "git add bugfix.txt", "git commit -m \"fix bug\""], [state(96, "onMain", "main ブランチにいる"), state(96, "bugfixTracked", "bugfix.txt が HEAD にコミット済み")], "main 上で bugfix.txt を修正し、`git add` と `git commit` で1つの修正として確定します。hotfix は影響範囲を小さく保つことが大切なので、関係するファイルだけをすぐ記録する手順が合っています。実務では修正後にテストしてから共有します。"),
  drill(97, "featureからタグまで", "feature/release で開発し、mainにマージして v2.0.0 タグを付けてください。", "開発ブランチ、マージ、タグ付けを順に行います。", ["git switch -c feature/release", "printf \"release\\n\" > release.txt", "git add release.txt", "git commit -m \"add release feature\"", "git switch main", "git merge --no-ff feature/release -m \"merge release\"", "git tag v2.0.0"], [state(97, "releaseTracked", "release.txt が HEAD にコミット済み"), state(97, "tagExists", "v2.0.0 タグがある")], "feature/release で release.txt をコミットしてから main に戻り、`--no-ff` で統合の記録を残します。最後に `git tag v2.0.0` を付けることで、リリース対象になった main の地点を固定できます。開発、統合、リリース印付けの順序を守るのが重要です。"),
  drill(98, "2機能統合", "feature/a と feature/b を順番に main へ統合してください。", "複数機能はmainで1本ずつマージします。", ["git merge feature/a", "git merge feature/b"], [state(98, "aMerged", "feature/a の変更が main に入っている"), state(98, "bMerged", "feature/b の変更が main に入っている")], "`git merge feature/a` と `git merge feature/b` を順に実行すると、main に2つの機能を段階的に統合できます。順番に取り込むことで、衝突や失敗がどの機能由来か切り分けやすくなります。統合後はログやテストで両方入ったことを確認します。"),
  drill(99, "hard reset復旧", "失われた recover.txt のコミットを reflog から復活させてください。", "reset済みでも reflog に以前のHEADが残っていれば、`git reset --hard <oid>` で戻せます。", ["git reflog", "git reset --hard ORIG_HEAD"], [state(99, "recoverTracked", "recover.txt が HEAD にコミット済み"), state(99, "recoverHead", "HEAD が recover.txt の復旧コミットに戻っている")], "`git reflog` は hard reset で見えなくなった以前の HEAD 位置を探す手がかりになります。`git reset --hard ORIG_HEAD` でその地点へ戻すと、recover.txt を含むコミットを再び先端にできます。現在の作業ツリーは上書きされるため、必要な変更があれば先に退避します。"),
  drill(100, "リリース準備総合", "feature/login で login.js を追加コミットし、.gitignore で `*.log` を除外し、mainにマージして注釈タグ v1.0.0 を付けてください。", "ブランチ開発、ignore設定、マージ、注釈タグを一連のリリース準備として実行します。", ["git switch -c feature/login", "printf \"export function login() { return true; }\\n\" > login.js", "git add login.js", "git commit -m \"add login\"", "printf \"*.log\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore logs\"", "git switch main", "git merge --no-ff feature/login -m \"merge login\"", "git tag -a v1.0.0 -m \"release v1.0.0\""], [state(100, "loginTracked", "login.js が HEAD にコミット済み"), state(100, "gitignore", ".gitignore に *.log がある"), state(100, "tagExists", "v1.0.0 タグがある")], "feature/login で機能追加とログ除外設定をコミットし、main に戻って `--no-ff` で統合します。最後の `git tag -a v1.0.0 -m ...` は、リリース地点に説明付きの注釈タグを付ける操作です。機能、設定、統合、リリース印を順に進めることで履歴が追いやすくなります。"),
];
