function state(id, key, label) {
  return { id: `drill${id}.${key}`, label, kind: "state" };
}

function action(id, key, label) {
  return { id: `drill${id}.${key}`, label, kind: "action" };
}

function drill(id, title, prompt, hint, answer, conditions) {
  return { id, title, prompt, hint, answer, conditions };
}

export const extraDrills = [
  drill(21, "衝突なしrebase", "main が進んだ状態で、feature ブランチを main の先端へ `git rebase main` で付け替えてください。", "feature に切り替えて `git rebase main` すると、feature の変更が main の最新コミットの後ろに積み直されます。", ["git switch feature", "git rebase main"], [state(21, "onFeature", "feature ブランチにいる"), state(21, "rebasedOntoMain", "feature が main の先端に付け替わっている")]),
  drill(22, "空コミット", "`git commit --allow-empty` で空コミットを1つ作ってください。", "`--allow-empty` はファイル変更なしでもコミットを作れます。", ["git commit --allow-empty -m \"empty checkpoint\""], [state(22, "message", "最新コミットのメッセージが empty checkpoint"), action(22, "allowEmptyUsed", "git commit --allow-empty を実行した")]),
  drill(23, "全変更をまとめる", "複数ファイルの変更を `git add -A` でまとめてステージし、コミットしてください。", "`git add -A` は追加・変更・削除をまとめてステージします。", ["printf \"alpha\\n\" > alpha.txt", "printf \"beta\\n\" > beta.txt", "git add -A", "git commit -m \"add alpha beta\""], [state(23, "filesTracked", "alpha.txt と beta.txt が HEAD にコミット済み"), action(23, "addAUsed", "git add -A を実行した")]),
  drill(24, "追跡済みを一括コミット", "追跡済みの README.md を編集し、`git commit -am` で一括コミットしてください。", "`git commit -am` は追跡済みファイルの変更をステージしてコミットします。", ["printf \"# My Project\\nupdated\\n\" > README.md", "git commit -am \"update readme\""], [state(24, "message", "最新コミットのメッセージが update readme"), action(24, "commitAmUsed", "git commit -am を実行した")]),
  drill(25, "2ファイルだけコミット", "one.txt / two.txt / three.txt のうち one.txt と two.txt だけをコミットしてください。", "コミットしたいファイルだけを `git add` に指定します。", ["git add one.txt two.txt", "git commit -m \"add selected files\""], [state(25, "selectedTracked", "one.txt と two.txt が HEAD にコミット済み"), state(25, "threeUntracked", "three.txt は未追跡のまま")]),
  drill(26, "amendで変更を追加", "README.md の追加変更を `git commit --amend --no-edit` で直前コミットに足してください。", "`--no-edit` はコミットメッセージを変えずに amend します。", ["printf \"# My Project\\namended\\n\" > README.md", "git add README.md", "git commit --amend --no-edit"], [state(26, "singleCommit", "コミット数が1つのまま"), action(26, "amendUsed", "git commit --amend --no-edit を実行した")]),
  drill(27, "amendで新ファイル追加", "note.txt を直前コミットに含めるよう `git commit --amend --no-edit` してください。", "新ファイルも `git add` してから amend できます。", ["printf \"note\\n\" > note.txt", "git add note.txt", "git commit --amend --no-edit"], [state(27, "noteTracked", "note.txt が HEAD にコミット済み"), state(27, "singleCommit", "コミット数が1つのまま")]),
  drill(28, "cherry-pickで取り込み", "feature にある `add report` コミットだけを main に `git cherry-pick feature` で取り込んでください。", "別ブランチの単独コミットは、main 側で `git cherry-pick <ブランチ名>` と指定して取り込めます。", ["git cherry-pick feature"], [state(28, "onMain", "main ブランチにいる"), state(28, "reportPicked", "report.txt のコミットが main に取り込まれている")]),
  drill(29, "git show HEAD", "`git show HEAD` で最新コミットを確認してください。", "`git show HEAD` は最新コミットの内容を表示します。", ["git show HEAD"], [state(29, "hasCommit", "1つ以上のコミットがある"), action(29, "showHeadUsed", "git show HEAD を実行した")]),
  drill(30, "git log -1", "`git log -1` で最新コミットを1件だけ表示してください。", "`git log -1` は最新の1件だけを表示します。", ["git log -1"], [state(30, "hasCommit", "1つ以上のコミットがある"), action(30, "logOneUsed", "git log -1 を実行した")]),

  drill(31, "未ステージ差分", "README.md を編集し、`git diff` で未ステージ差分を確認してください。", "`git diff` はまだステージしていない変更を表示します。", ["printf \"# My Project\\ndiff\\n\" > README.md", "git diff"], [state(31, "workingDiff", "README.md に未ステージ差分がある"), action(31, "diffUsed", "git diff を実行した")]),
  drill(32, "ステージ済み差分", "README.md を編集して add し、`git diff --staged` で確認してください。", "`git diff --staged` はステージ済み差分を表示します。", ["printf \"# My Project\\nstaged\\n\" > README.md", "git add README.md", "git diff --staged"], [state(32, "stagedDiff", "README.md にステージ済み差分がある"), action(32, "diffStagedUsed", "git diff --staged を実行した")]),
  drill(33, "HEADとの差分", "README.md を編集し、`git diff HEAD` で全差分を確認してください。", "`git diff HEAD` は作業ツリーと最新コミットの差分を表示します。", ["printf \"# My Project\\nhead diff\\n\" > README.md", "git diff HEAD"], [state(33, "headDiff", "README.md が HEAD から変更されている"), action(33, "diffHeadUsed", "git diff HEAD を実行した")]),
  drill(34, "直近コミット差分", "`git diff HEAD~1 HEAD` で直近コミットの差分を確認してください。", "`HEAD~1 HEAD` を指定すると直近1コミット分の差分を見られます。", ["git diff HEAD~1 HEAD"], [state(34, "twoCommits", "2つ以上のコミットがある"), action(34, "diffRangeUsed", "git diff HEAD~1 HEAD を実行した")]),
  drill(35, "onelineログ", "`git log --oneline` で履歴を短く表示してください。", "`--oneline` はコミットを1行ずつ表示します。", ["git log --oneline"], [state(35, "hasCommit", "1つ以上のコミットがある"), action(35, "logOnelineUsed", "git log --oneline を実行した")]),
  drill(36, "stat付きログ", "`git log --stat` で変更ファイル数つきの履歴を確認してください。", "`--stat` はコミットごとの変更量を表示します。", ["git log --stat"], [state(36, "hasCommit", "1つ以上のコミットがある"), action(36, "logStatUsed", "git log --stat を実行した")]),
  drill(37, "2件ログ", "`git log -n 2` で最新2件の履歴を確認してください。", "`-n 2` は表示するコミット数を2件に絞ります。", ["git log -n 2"], [state(37, "twoCommits", "2つ以上のコミットがある"), action(37, "logN2Used", "git log -n 2 を実行した")]),
  drill(38, "特定コミットをshow", "最新コミットのOIDを使って `git show <oid>` を実行してください。", "`git rev-parse HEAD` でOIDを取り、`git show` に渡せます。", ["git show $(git rev-parse HEAD)"], [state(38, "hasCommit", "1つ以上のコミットがある"), action(38, "showUsed", "git show <oid> を実行した")]),
  drill(39, "graphログ", "`git log --oneline --graph` でグラフ表示してください。", "`--graph` はブランチやマージの形をASCIIグラフで表示します。", ["git log --oneline --graph"], [state(39, "hasCommit", "1つ以上のコミットがある"), action(39, "logGraphUsed", "git log --oneline --graph を実行した")]),
  drill(40, "ファイル別履歴", "`git log -- README.md` で README.md の履歴だけを表示してください。", "`git log -- ファイル名` は対象ファイルに関係する履歴だけを表示します。", ["git log -- README.md"], [state(40, "readmeTracked", "README.md が HEAD にコミット済み"), action(40, "logFileUsed", "git log -- README.md を実行した")]),

  drill(41, "ブランチ作成だけ", "`git branch experiment` で切り替えずにブランチを作ってください。", "`git branch 名前` は現在位置にブランチを作るだけで切り替えません。", ["git branch experiment"], [state(41, "branchExists", "experiment ブランチがある"), state(41, "onMain", "main ブランチにいる")]),
  drill(42, "switch -c", "`git switch -c feature/a` でブランチを作って切り替えてください。", "`git switch -c` は作成と切り替えを同時に行います。", ["git switch -c feature/a"], [state(42, "branchExists", "feature/a ブランチがある"), state(42, "onBranch", "feature/a ブランチにいる")]),
  drill(43, "checkout -b", "`git checkout -b feature/b` でブランチを作って切り替えてください。", "`git checkout -b` は古くから使われる作成・切り替えコマンドです。", ["git checkout -b feature/b"], [state(43, "branchExists", "feature/b ブランチがある"), state(43, "onBranch", "feature/b ブランチにいる")]),
  drill(44, "リモート確認", "`git remote -v` で origin の接続先を確認してください。", "`git remote -v` は fetch/push に使うリモートURLを表示します。", ["git remote -v"], [state(44, "originConfigured", "origin リモートが設定されている"), action(44, "remoteVUsed", "git remote -v を実行した")]),
  drill(45, "mainに戻る", "作業ブランチから main に戻ってください。", "`git switch main` で main ブランチへ戻れます。", ["git switch main"], [state(45, "onMain", "main ブランチにいる"), state(45, "featureExists", "feature ブランチが残っている")]),
  drill(46, "マージ済み削除", "マージ済みの feature ブランチを `git branch -d` で削除してください。", "`-d` はマージ済みブランチを安全に削除します。", ["git branch -d feature"], [state(46, "featureGone", "feature ブランチが残っていない"), action(46, "branchDeleteUsed", "git branch -d を実行した")]),
  drill(47, "未マージ強制削除", "未マージの wip ブランチを `git branch -D` で強制削除してください。", "`-D` は未マージでも削除する強い操作です。", ["git branch -D wip"], [state(47, "wipGone", "wip ブランチが残っていない"), action(47, "branchForceDeleteUsed", "git branch -D を実行した")]),
  drill(48, "ブランチ改名", "`git branch -m feature/old feature/new` でブランチ名を変えてください。", "`git branch -m 旧名 新名` でブランチを改名できます。", ["git branch -m feature/old feature/new"], [state(48, "newExists", "feature/new ブランチがある"), state(48, "oldGone", "feature/old ブランチが残っていない")]),
  drill(49, "初回push", "`git push -u origin main` で main を origin に送信し、上流ブランチを設定してください。", "`-u` を付けると次回以降 `git push` / `git pull` だけで origin/main と同期しやすくなります。", ["git push -u origin main"], [state(49, "originMainHasHead", "origin/main が現在の main を指している"), state(49, "mainUpstream", "main の上流が origin/main に設定されている")]),
  drill(50, "featureを2コミット進める", "feature ブランチで2つコミットを作ってください。", "ブランチへ切り替えてから通常通り2回コミットします。", ["git switch feature", "printf \"one\\n\" > f1.txt", "git add f1.txt", "git commit -m \"feature one\"", "printf \"two\\n\" > f2.txt", "git add f2.txt", "git commit -m \"feature two\""], [state(50, "onFeature", "feature ブランチにいる"), state(50, "aheadTwo", "feature が main より2つ以上進んでいる")]),
  drill(51, "特定コミットから分岐", "1つ前のコミットから `git switch -c rescue HEAD~1` でブランチを切ってください。", "`git switch -c 名前 <開始点>` で任意のコミットから分岐できます。", ["git switch -c rescue HEAD~1"], [state(51, "branchExists", "rescue ブランチがある"), state(51, "onBranch", "rescue ブランチにいる")]),
  drill(52, "現在ブランチ名", "`git branch --show-current` で現在のブランチ名を確認してください。", "`--show-current` は今いるブランチ名だけを表示します。", ["git branch --show-current"], [state(52, "onMain", "main ブランチにいる"), action(52, "showCurrentUsed", "git branch --show-current を実行した")]),
  drill(53, "hotfixブランチ", "main から hotfix ブランチを作って切り替えてください。", "`git switch -c hotfix` で main から修正用ブランチを作れます。", ["git switch -c hotfix"], [state(53, "hotfixExists", "hotfix ブランチがある"), state(53, "onHotfix", "hotfix ブランチにいる")]),
  drill(54, "別ファイルをコミット", "feature ブランチに切り替え、feature.txt をコミットしてください。", "ブランチを切り替えると、そのブランチ専用の変更を作れます。", ["git switch feature", "printf \"feature\\n\" > feature.txt", "git add feature.txt", "git commit -m \"add feature file\""], [state(54, "onFeature", "feature ブランチにいる"), state(54, "featureFileTracked", "feature.txt が HEAD にコミット済み")]),
  drill(55, "直前ブランチへ戻る", "`git switch -` で直前にいたブランチへ戻ってください。", "`git switch -` は直前のブランチへ戻るショートカットです。", ["git switch -"], [state(55, "onMain", "main ブランチに戻っている"), action(55, "switchDashUsed", "git switch - を実行した")]),

  drill(56, "FFマージ", "main に feature を fast-forward マージしてください。", "`git merge --ff-only feature` はFFできる時だけ履歴を進めます。", ["git merge --ff-only feature"], [state(56, "onMain", "main ブランチにいる"), state(56, "featureMerged", "feature の変更が main に入っている")]),
  drill(57, "no-ffマージ", "`git merge --no-ff feature` でマージコミットを作ってください。", "`--no-ff` はFF可能でもマージコミットを残します。", ["git merge --no-ff feature -m \"merge feature\""], [state(57, "onMain", "main ブランチにいる"), state(57, "mergeCommit", "マージコミットが作られている")]),
  drill(58, "README衝突解決", "README.md の衝突を解決して feature をマージしてください。", "衝突マーカーを消して `git add`、最後に `git commit` します。", ["git merge feature", "printf \"# My Project\\nmain line\\nfeature line\\n\" > README.md", "git add README.md", "git commit -m \"merge feature\""], [state(58, "noMarkers", "README.md に衝突マーカーがない"), state(58, "mergeCommit", "マージコミットが作られている")]),
  drill(59, "別ファイル衝突解決", "config.txt の衝突を解決して feature をマージしてください。", "README以外でも解決手順は同じです。", ["git merge feature", "printf \"mode=main\\nmode=feature\\n\" > config.txt", "git add config.txt", "git commit -m \"merge config\""], [state(59, "noMarkers", "config.txt に衝突マーカーがない"), state(59, "mergeCommit", "マージコミットが作られている")]),
  drill(60, "マージ中止", "衝突したマージを `git merge --abort` で中止してください。", "`git merge --abort` はマージ開始前の状態へ戻します。", ["git merge feature", "git merge --abort"], [state(60, "clean", "作業ツリーが clean"), action(60, "mergeAbortUsed", "git merge --abort を実行した")]),
  drill(61, "3つ目のブランチをマージ", "feature/c を main にマージしてください。", "対象ブランチ名を指定して `git merge feature/c` します。", ["git merge feature/c"], [state(61, "onMain", "main ブランチにいる"), state(61, "cMerged", "feature/c の変更が main に入っている")]),
  drill(62, "マージ後ログ確認", "feature をマージし、`git log --oneline` で確認してください。", "マージ後の履歴確認には `git log --oneline` が便利です。", ["git merge --ff-only feature", "git log --oneline"], [state(62, "featureMerged", "feature の変更が main に入っている"), action(62, "logOnelineUsed", "git log --oneline を実行した")]),
  drill(63, "pullで取り込む", "origin/main にある teammate.txt の更新を `git pull` で取り込んでください。", "ローカル main が origin/main より遅れている時は `git pull` で fetch と統合をまとめて実行できます。", ["git pull"], [state(63, "pulledTeammate", "teammate.txt が main に取り込まれている"), state(63, "mainMatchesOrigin", "main と origin/main が同じコミットを指している")]),
  drill(64, "2機能を順にマージ", "feature/a と feature/b を順番に main へマージしてください。", "複数ブランチは1本ずつ `git merge` します。", ["git merge feature/a", "git merge feature/b"], [state(64, "aMerged", "feature/a の変更が main に入っている"), state(64, "bMerged", "feature/b の変更が main に入っている")]),
  drill(65, "通常マージコミット", "main 側も進んだ状態で feature を通常マージし、マージコミットを作ってください。", "双方が進んでいる場合、通常の `git merge` はマージコミットを作ります。", ["git merge feature -m \"merge feature\""], [state(65, "onMain", "main ブランチにいる"), state(65, "mergeCommit", "マージコミットが作られている")]),

  drill(66, "編集破棄", "README.md の編集を `git restore README.md` で破棄してください。", "`git restore <file>` は未ステージ編集を破棄します。", ["git restore README.md"], [state(66, "clean", "作業ツリーが clean"), action(66, "restoreUsed", "git restore を実行した")]),
  drill(67, "ステージ解除", "README.md のステージだけを `git restore --staged README.md` で解除してください。", "`--staged` は内容を残してステージだけ外します。", ["git restore --staged README.md"], [state(67, "noStaged", "ステージ済み差分がない"), state(67, "workingDiff", "作業ツリーに変更が残っている")]),
  drill(68, "soft reset", "`git reset --soft HEAD~1` で直前コミットを戻し、変更をステージに残してください。", "`--soft` はHEADだけを戻すので変更はステージに残ります。", ["git reset --soft HEAD~1"], [state(68, "oneCommit", "コミット数が1つ戻っている"), state(68, "staged", "変更がステージに残っている")]),
  drill(69, "mixed reset", "`git reset --mixed HEAD~1` で直前コミットを戻し、変更を未ステージにしてください。", "`--mixed` はHEADとインデックスを戻し、作業ツリーに変更を残します。", ["git reset --mixed HEAD~1"], [state(69, "oneCommit", "コミット数が1つ戻っている"), state(69, "workingDiff", "変更が未ステージに残っている")]),
  drill(70, "hard reset", "`git reset --hard HEAD~1` で直前コミットと変更を完全に戻してください。", "`--hard` は作業ツリーも消す強い操作です。必要な変更がない時だけ使います。", ["git reset --hard HEAD~1"], [state(70, "oneCommit", "コミット数が1つ戻っている"), state(70, "clean", "作業ツリーが clean")]),
  drill(71, "revertで打ち消し", "`git revert HEAD --no-edit` で直前コミットを打ち消してください。", "`git revert` は履歴を消さずに逆変更のコミットを追加します。", ["git revert HEAD --no-edit"], [state(71, "badGone", "bad.txt が消えている"), state(71, "revertCommit", "revertコミットが追加されている")]),
  drill(72, "別コミットをrevert", "`git revert HEAD~1 --no-edit` で1つ前のコミットを打ち消してください。", "HEAD以外のコミットも指定して revert できます。", ["git revert HEAD~1 --no-edit"], [state(72, "oldGone", "old-bug.txt が消えている"), state(72, "revertCommit", "revertコミットが追加されている")]),
  drill(73, "reflog確認", "`git reflog` でHEAD移動履歴を確認してください。", "`git reflog` はreset前後のHEAD位置を探す時に便利です。", ["git reflog"], [state(73, "hasCommit", "1つ以上のコミットがある"), action(73, "reflogUsed", "git reflog を実行した")]),
  drill(74, "reflogから復活", "失われた recover.txt のコミットを reflog から見つけ、`git reset --hard <oid>` か `git reset --hard ORIG_HEAD` で復活させてください。", "`git reflog` で reset 前の位置を探し、そのOIDへ `git reset --hard` します。", ["git reflog", "git reset --hard ORIG_HEAD"], [state(74, "recoverTracked", "recover.txt が HEAD にコミット済み"), state(74, "recoverHead", "HEAD が recover.txt の復旧コミットに戻っている")]),
  drill(75, "削除ファイル復元", "削除した README.md を `git restore README.md` で復元してください。", "追跡済みファイルの削除も `git restore` でHEADから戻せます。", ["git restore README.md"], [state(75, "readmeExists", "README.md が存在する"), state(75, "clean", "作業ツリーが clean")]),
  drill(76, "fetchして確認", "origin/main の新着コミットを `git fetch` で取得し、`git log --oneline origin/main` で確認してください。", "`git fetch` は作業ブランチを動かさずにリモート追跡ブランチだけ更新します。", ["git fetch origin", "git log --oneline origin/main"], [state(76, "originFetched", "origin/main に remote-only.txt のコミットが見えている"), action(76, "logOriginUsed", "git log origin/main を実行した")]),
  drill(77, "reset HEADでアンステージ", "README.md を `git reset HEAD README.md` でアンステージしてください。", "`git reset HEAD <file>` は古くから使われるステージ解除です。", ["git reset HEAD README.md"], [state(77, "noStaged", "ステージ済み差分がない"), state(77, "workingDiff", "作業ツリーに変更が残っている")]),
  drill(78, "未追跡をclean", "未追跡の scratch.txt を `git clean -f` で削除してください。", "`git clean -f` は未追跡ファイルを削除する強い操作です。", ["git clean -f"], [state(78, "scratchGone", "scratch.txt が存在しない"), action(78, "cleanUsed", "git clean -f を実行した")]),

  drill(79, "stashで退避", "README.md の編集を `git stash` で退避してください。", "`git stash` は作業中の変更を一時保存して作業ツリーをcleanにします。", ["git stash"], [state(79, "clean", "作業ツリーが clean"), action(79, "stashUsed", "git stash を実行した")]),
  drill(80, "stash pop", "退避済みの作業を `git stash pop` で戻してください。", "`git stash pop` はstashを適用して一覧から取り除きます。", ["git stash pop"], [state(80, "workingDiff", "作業ツリーに変更が戻っている"), action(80, "stashPopUsed", "git stash pop を実行した")]),
  drill(81, "stash list", "`git stash list` で退避一覧を確認してください。", "`git stash list` は保存済みstashを一覧表示します。", ["git stash list"], [state(81, "stashExists", "stash が1件以上ある"), action(81, "stashListUsed", "git stash list を実行した")]),
  drill(82, "stash apply", "`git stash apply` で退避を作業ツリーに適用してください。", "`git stash apply` はstashを残したまま変更を戻します。", ["git stash apply"], [state(82, "workingDiff", "作業ツリーに変更が戻っている"), state(82, "stashExists", "stash が残っている")]),
  drill(83, "stash drop", "`git stash drop` で退避を1件削除してください。", "`git stash drop` は指定したstashを一覧から削除します。", ["git stash drop"], [state(83, "stashEmpty", "stash が空になっている"), action(83, "stashDropUsed", "git stash drop を実行した")]),
  drill(84, "未追跡もstash", "未追跡の draft.txt も含めて `git stash -u` で退避してください。", "`git stash -u` は未追跡ファイルも退避対象にします。", ["git stash -u"], [state(84, "draftGone", "draft.txt が作業ツリーから消えている"), action(84, "stashUUsed", "git stash -u を実行した")]),
  drill(85, "stashして切替え", "変更をstashし、featureへ切り替えてから main に戻ってください。", "変更が邪魔な時はstashしてからブランチを切り替えます。", ["git stash", "git switch feature", "git switch main"], [state(85, "onMain", "main ブランチに戻っている"), action(85, "stashUsed", "git stash を実行した")]),
  drill(86, "cherry-pickで修正移植", "hotfix ブランチの `fix config` コミットを main に cherry-pick してください。", "緊急修正など、必要な1コミットだけを別ブランチへ移す時に `git cherry-pick` を使います。", ["git cherry-pick hotfix"], [state(86, "onMain", "main ブランチにいる"), state(86, "configPicked", "config.txt の修正コミットが main に取り込まれている")]),
  drill(87, "stash show", "`git stash show` で退避内容の概要を確認してください。", "`git stash show` はstashの変更概要を表示します。", ["git stash show"], [state(87, "stashExists", "stash が1件以上ある"), action(87, "stashShowUsed", "git stash show を実行した")]),
  drill(88, "stash clear", "`git stash clear` でstashをすべて削除してください。", "`git stash clear` はstash一覧を全削除します。", ["git stash clear"], [state(88, "stashEmpty", "stash が空になっている"), action(88, "stashClearUsed", "git stash clear を実行した")]),

  drill(89, "軽量タグ", "`git tag v1.0.0` で軽量タグを作ってください。", "`git tag タグ名` は現在のコミットへ軽量タグを付けます。", ["git tag v1.0.0"], [state(89, "tagExists", "v1.0.0 タグがある"), action(89, "tagUsed", "git tag v1.0.0 を実行した")]),
  drill(90, "注釈タグ", "`git tag -a v1.1.0 -m \"release v1.1.0\"` で注釈タグを作ってください。", "`-a -m` を使うとメッセージ付きの注釈タグを作れます。", ["git tag -a v1.1.0 -m \"release v1.1.0\""], [state(90, "tagExists", "v1.1.0 タグがある"), action(90, "annotatedTagUsed", "git tag -a を実行した")]),
  drill(91, "タグ一覧", "`git tag` でタグ一覧を確認してください。", "`git tag` はタグ名の一覧を表示します。", ["git tag"], [state(91, "tagExists", "v1.0.0 タグがある"), action(91, "tagListUsed", "git tag を実行した")]),
  drill(92, "タグ削除", "`git tag -d v1.0.0` でタグを削除してください。", "`git tag -d タグ名` はローカルタグを削除します。", ["git tag -d v1.0.0"], [state(92, "tagGone", "v1.0.0 タグが残っていない"), action(92, "tagDeleteUsed", "git tag -d を実行した")]),
  drill(93, "logをignore", ".gitignore で `*.log` を除外してコミットしてください。", "無視パターンは `.gitignore` に書き、.gitignore自体はコミットします。", ["printf \"*.log\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore logs\""], [state(93, "gitignore", ".gitignore に *.log がある"), state(93, "debugIgnored", "debug.log がstatusに出ない")]),
  drill(94, "distをignore", ".gitignore で `dist/` ディレクトリを除外してコミットしてください。", "ディレクトリ除外は `dist/` のように末尾スラッシュを使います。", ["printf \"dist/\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore dist\""], [state(94, "gitignore", ".gitignore に dist/ がある"), state(94, "distIgnored", "dist/app.js がstatusに出ない")]),
  drill(95, "追跡解除", "`git rm --cached secret.txt` でファイルを残したまま追跡解除してください。", "`--cached` は作業ツリーのファイルを残してGitの追跡だけ外します。", ["git rm --cached secret.txt"], [state(95, "secretUntracked", "secret.txt が追跡対象から外れている"), state(95, "secretExists", "secret.txt は作業ツリーに残っている")]),

  drill(96, "hotfix実務フロー", "main で bugfix.txt を修正して1コミットしてください。", "hotfixは小さく修正し、すぐコミットするのが基本です。", ["printf \"fixed\\n\" > bugfix.txt", "git add bugfix.txt", "git commit -m \"fix bug\""], [state(96, "onMain", "main ブランチにいる"), state(96, "bugfixTracked", "bugfix.txt が HEAD にコミット済み")]),
  drill(97, "featureからタグまで", "feature/release で開発し、mainにマージして v2.0.0 タグを付けてください。", "開発ブランチ、マージ、タグ付けを順に行います。", ["git switch -c feature/release", "printf \"release\\n\" > release.txt", "git add release.txt", "git commit -m \"add release feature\"", "git switch main", "git merge --no-ff feature/release -m \"merge release\"", "git tag v2.0.0"], [state(97, "releaseTracked", "release.txt が HEAD にコミット済み"), state(97, "tagExists", "v2.0.0 タグがある")]),
  drill(98, "2機能統合", "feature/a と feature/b を順番に main へ統合してください。", "複数機能はmainで1本ずつマージします。", ["git merge feature/a", "git merge feature/b"], [state(98, "aMerged", "feature/a の変更が main に入っている"), state(98, "bMerged", "feature/b の変更が main に入っている")]),
  drill(99, "hard reset復旧", "失われた recover.txt のコミットを reflog から復活させてください。", "reset済みでも reflog に以前のHEADが残っていれば、`git reset --hard <oid>` で戻せます。", ["git reflog", "git reset --hard ORIG_HEAD"], [state(99, "recoverTracked", "recover.txt が HEAD にコミット済み"), state(99, "recoverHead", "HEAD が recover.txt の復旧コミットに戻っている")]),
  drill(100, "リリース準備総合", "feature/login で login.js を追加コミットし、.gitignore で `*.log` を除外し、mainにマージして注釈タグ v1.0.0 を付けてください。", "ブランチ開発、ignore設定、マージ、注釈タグを一連のリリース準備として実行します。", ["git switch -c feature/login", "printf \"export function login() { return true; }\\n\" > login.js", "git add login.js", "git commit -m \"add login\"", "printf \"*.log\\n\" > .gitignore", "git add .gitignore", "git commit -m \"ignore logs\"", "git switch main", "git merge --no-ff feature/login -m \"merge login\"", "git tag -a v1.0.0 -m \"release v1.0.0\""], [state(100, "loginTracked", "login.js が HEAD にコミット済み"), state(100, "gitignore", ".gitignore に *.log がある"), state(100, "tagExists", "v1.0.0 タグがある")]),
];
